# Generated by Django 2.2.5 on 2019-09-29 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('join_api', '0003_auto_20190925_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=500)),
                ('design_photho', models.ImageField(upload_to='designs')),
                ('design_style', models.CharField(max_length=200)),
                ('design_desc', models.CharField(max_length=1000)),
                ('tatt_id', models.ForeignKey(db_column='tatt_id', on_delete=django.db.models.deletion.CASCADE, to='join_api.Join_tattist')),
            ],
        ),
    ]
