# Generated by Django 2.2.5 on 2019-09-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design',
            name='design_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='design',
            name='design_spent_time',
            field=models.IntegerField(default=0),
        ),
    ]
