# Generated by Django 2.2.5 on 2019-09-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='tatt_id',
            field=models.ForeignKey(db_column='tatt_id', on_delete=django.db.models.deletion.CASCADE, to='login_api.User'),
        ),
    ]
