# Generated by Django 2.2.5 on 2019-09-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20191001_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='design_photho',
            new_name='design_photo',
        ),
    ]
