# Generated by Django 2.2.5 on 2019-09-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='join_tattist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatt_work', models.CharField(max_length=300)),
                ('tatt_addr', models.CharField(max_length=200)),
                ('tatt_intro', models.CharField(max_length=200)),
                ('tatt_time', models.CharField(max_length=200)),
                ('tatt_date', models.CharField(max_length=200)),
                ('tatt_profile', models.CharField(max_length=300)),
            ],
        ),
    ]
