# Generated by Django 2.2.5 on 2019-09-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_tattist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatt_work', models.CharField(blank=True, max_length=1000, null=True)),
                ('tatt_addr', models.CharField(max_length=200)),
                ('tatt_intro', models.CharField(max_length=200)),
                ('tatt_time', models.CharField(max_length=200)),
                ('tatt_date', models.CharField(max_length=200)),
                ('tatt_profile', models.CharField(max_length=1000)),
                ('tatt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_api.User')),
            ],
        ),
    ]
