# Generated by Django 2.2.5 on 2019-09-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_tattist',
            name='tatt_id',
            field=models.CharField(max_length=50),
        ),
    ]
