# Generated by Django 2.2.5 on 2019-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0002_join_tattist_tatt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_tattist',
            name='tatt_work',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
