# Generated by Django 2.2.5 on 2019-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0003_auto_20190917_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_tattist',
            name='tatt_profile',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='join_tattist',
            name='tatt_work',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
