# Generated by Django 2.2.5 on 2019-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0003_auto_20190925_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_tattist',
            name='back_img',
            field=models.ImageField(null=True, upload_to='backgrounds'),
        ),
    ]
