# Generated by Django 2.2.5 on 2019-09-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0004_auto_20190918_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_tattist',
            name='tatt_profile',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='join_tattist',
            name='tatt_work',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
