# Generated by Django 2.2.5 on 2019-11-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0004_join_tattist_back_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_tattist',
            name='back_img',
            field=models.ImageField(default=' ', upload_to='backgrounds'),
            preserve_default=False,
        ),
    ]
