# Generated by Django 2.2.5 on 2019-11-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_api', '0006_auto_20191103_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_tattist',
            name='back_img',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
    ]
