# Generated by Django 2.2.5 on 2019-10-21 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0004_auto_20191021_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.CharField(max_length=100)),
                ('book_date', models.CharField(max_length=100)),
                ('book_time', models.CharField(max_length=20)),
                ('book_price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('book_part', models.CharField(max_length=50)),
                ('book_size', models.CharField(max_length=50)),
                ('book_comm', models.CharField(max_length=500)),
                ('book_photo', models.CharField(max_length=500)),
                ('book_tatt', models.CharField(max_length=100)),
                ('design_id', models.ForeignKey(db_column='design_id', on_delete=django.db.models.deletion.CASCADE, to='design.Design')),
            ],
        ),
    ]
