# Generated by Django 2.2.5 on 2019-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191022_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_place',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
