# Generated by Django 2.2.5 on 2019-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rv_writer', models.CharField(max_length=100)),
                ('rv_contents', models.CharField(max_length=500)),
                ('rv_date', models.DateField(auto_now=True)),
                ('rv_photo', models.ImageField(null=True, upload_to='review')),
                ('rv_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
