# Generated by Django 2.2.5 on 2019-11-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20191021_1909'),
        ('join_api', '0004_join_tattist_back_img'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rv_design',
            field=models.ForeignKey(db_column='rv_design', default='', on_delete=django.db.models.deletion.CASCADE, to='design.Design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rv_tatt',
            field=models.ForeignKey(db_column='rv_tatt', default=1, on_delete=django.db.models.deletion.CASCADE, to='join_api.Join_tattist'),
            preserve_default=False,
        ),
    ]
