# Generated by Django 2.2.5 on 2019-11-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20191102_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rv_rate',
            field=models.FloatField(default=0),
        ),
    ]
