# Generated by Django 2.2.5 on 2019-11-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_rv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rv_rate',
            field=models.CharField(max_length=10),
        ),
    ]
