# Generated by Django 2.2.5 on 2019-09-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=30)),
                ('role_tatt', models.BooleanField(default=False)),
            ],
        ),
    ]
