# Generated by Django 2.2.5 on 2019-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('user_pw', models.CharField(max_length=30)),
                ('role_tatt', models.BooleanField(default=False)),
            ],
        ),
    ]
