# Generated by Django 2.2.5 on 2019-10-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0001_initial'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='tatt_id',
            field=models.ForeignKey(db_column='tatt_id', default='', on_delete=django.db.models.deletion.CASCADE, to='login_api.User'),
            preserve_default=False,
        ),
    ]
